# Generated by Django 4.1 on 2022-08-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, null=True, unique=True, verbose_name="URL"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, null=True, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work.room",
                        verbose_name="room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "room_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work.roomwork",
                        verbose_name="room_work",
                    ),
                ),
                (
                    "worker_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="worker.workershift",
                        verbose_name="worker",
                    ),
                ),
            ],
        ),
    ]
