# Generated by Django 4.1 on 2022-08-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_remove_work_room_work_work_room_work"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="done",
        ),
        migrations.CreateModel(
            name="WorkerJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done", models.BooleanField(default=False)),
                (
                    "room_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work.roomwork",
                        verbose_name="room_work",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="work",
            name="room_work",
            field=models.ManyToManyField(
                to="work.workerjob", verbose_name="worker_job"
            ),
        ),
    ]
