# Generated by Django 4.1 on 2022-08-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0003_remove_work_done_workerjob_alter_work_room_work"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="room_work",
            new_name="worker_job",
        ),
    ]
