# Generated by Django 4.1 on 2022-08-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workershift",
            name="shift",
            field=models.CharField(
                choices=[
                    ("morning_shift", "morning shift"),
                    ("day_shift", "day shift"),
                    ("evening_shift", "evening shift"),
                    ("night_shift", "night shift"),
                ],
                max_length=100,
            ),
        ),
    ]
