# Generated by Django 4.1 on 2022-08-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0002_alter_workershift_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workershift",
            name="shift",
            field=models.CharField(
                choices=[
                    ("morning shift", "morning shift"),
                    ("day shift", "day shift"),
                    ("evening shift", "evening shift"),
                    ("night shift", "night shift"),
                ],
                max_length=100,
            ),
        ),
    ]
