# Generated by Django 4.1 on 2022-09-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0003_alter_workershift_shift"),
    ]

    operations = [
        migrations.AddField(
            model_name="workershift",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
