# Generated by Django 4.1 on 2022-09-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0008_alter_freedates_setup_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freedates",
            name="approved",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
