# Generated by Django 4.1 on 2022-09-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0009_alter_freedates_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freedates",
            name="approved",
            field=models.CharField(default="null", max_length=100),
        ),
    ]
