# Generated by Django 4.1 on 2022-09-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0010_alter_freedates_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freedates",
            old_name="end_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="freedates",
            name="start_date",
        ),
    ]
