# Generated by Django 4.1 on 2022-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0011_rename_end_date_freedates_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freedates",
            old_name="date",
            new_name="end_date",
        ),
        migrations.AddField(
            model_name="freedates",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
