# Generated by Django 4.1 on 2022-09-16 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("worker", "0012_rename_date_freedates_end_date_freedates_start_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="freedates",
            unique_together={("user", "start_date", "end_date")},
        ),
    ]
